# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: build

# Trigger workflow on any push or pull request.
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  lint:
    name: Check code with formatter and linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Install Node interpreter
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Cache Node packages
        uses: actions/cache@v3
        with:
          path: node_modules
          key: >-
            node-20_${{ runner.os }}_npm-${{ hashFiles('package-lock.json') }}
      - name: Install Node packages
        run: |
          node --version
          npm --version
          npm ci
      - name: Check format of configuration files
        run: npm run prettier:test
      - name: Install Shfmt
        run: |
          shfmt_version="$(curl -LSfs https://formulae.brew.sh/api/formula/shfmt.json | jq --raw-output .versions.stable)"
          sudo curl -LSfs "https://github.com/mvdan/sh/releases/download/v${shfmt_version}/shfmt_v${shfmt_version}_linux_amd64" --output /usr/local/bin/shfmt
          sudo chmod 755 /usr/local/bin/shfmt
      - name: Check format of shell scripts
        run: npm run shfmt:test
      - name: Install ShellCheck
        run: sudo apt-get install --yes shellcheck
      - name: Run ShellCheck on shell scripts
        run: npm run shellcheck:test

  test-bash:
    name: Run unit tests for Bash scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Install Node interpreter
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Cache Node packages
        uses: actions/cache@v3
        with:
          path: node_modules
          key: >-
            node-20_${{ runner.os }}_npm-${{ hashFiles('package-lock.json') }}
      - name: Install Node packages
        run: |
          node --version
          npm --version
          npm ci
      - name: Run Bash unit tests with Bats
        run: npm run bats:test

  test-powershell:
    name: Run linter and unit tests for PowerShell scripts
    runs-on: windows-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Install PSScriptAnalyzer
        run: Install-Module -Name PSScriptAnalyzer -Force
        shell: pwsh
      - name: Run PSScriptAnalyzer format lints on all PowerShell scripts
        run: Invoke-ScriptAnalyzer -Recurse -Path . -Settings CodeFormatting
        shell: pwsh
      - name: Install Pester
        run: Install-Module -Name Pester -Force
        shell: pwsh
      - name: Run PowerShell unit tests with Pester
        run: Invoke-Pester -Output Detailed ./tests/unit/
        shell: pwsh
