# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

---
name: pages

# Makes workflow run on push to the main branch.
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        default: false
        description: Use Tmate session for debugging
        type: boolean

env:
  DENO_DIR: "${{ github.workspace }}/.vendor/deno"

jobs:
  doc:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: deno-${{ runner.os }}-${{ hashFiles('deno.lock') }}
          path: |
            .vendor
            node_modules
      - name: Install Just
        run: src/install/just.sh --dest /usr/local/bin
      - name: Run commands
        run: just setup doc
      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_dir: build/site
      - name: Setup Tmate session if debug enabled
        if: >-
          ${{ always() && github.event_name == 'workflow_dispatch' &&
          inputs.debug }}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3
