# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

---
name: release

# Makes workflow run on Git tag.
on:
  push:
    tags:
      - "**"

jobs:
  release:
    name: Make GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body: >-
            See the [changelog](https://github.com/scruffaluff/scripts/blob/${{
            github.ref_name }}/CHANGELOG.md) for more information.
          name: Scripts ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
